name: playwright

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.40.1-jammy
    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc

    - name: Install FC dependencies
      run: npm i

    - name: Build FC
      run: npm run build

    - name: Install example app npm dependencies
      run: npm i
      working-directory: ./example_app/server

    - name: Install playwright dependencies
      run: npm i
      working-directory: ./example_app/tests-e2e

    - name: Run Playwright tests
      working-directory: ./example_app/tests-e2e
      run: npx playwright test

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: ./example_app/tests-e2e/playwright-report
        retention-days: 30
